export const recipeTypes = {
  RECIPE_GET_ITEMS: "API:RECIPE_GET_ITEMS",
  RECIPE_GET_ITEMS_SUCCESS: "RECIPE_GET_ITEMS_SUCCESS",
  RECIPE_GET_ITEMS_FAILURE: "RECIPE_GET_ITEMS_FAILURE",

  RECIPE_GET_ITEM: "API:RECIPE_GET_ITEM",
  RECIPE_GET_ITEM_SUCCESS: "RECIPE_GET_ITEM_SUCCESS",
  RECIPE_GET_ITEM_FAILURE: "RECIPE_GET_ITEM_FAILURE",

  CHANGE_LIKE_ITEM: 'API:CHANGE_LIKE_ITEM',
  CHANGE_LIKE_ITEM_SUCCESS: 'CHANGE_LIKE_ITEM_SUCCESS',
  CHANGE_LIKE_ITEM_FAILURE: 'CHANGE_LIKE_ITEM_FAILURE',
};
