export const ingredientTypes = {
  INGREDIENT_GET_ITEMS: 'API:INGREDIENT_GET_ITEMS',
  INGREDIENT_GET_ITEMS_SUCCESS: 'INGREDIENT_GET_ITEMS_SUCCESS',
  INGREDIENT_GET_ITEMS_FAILURE: 'INGREDIENT_GET_ITEMS_FAILURE'
}