export const authTypes = {
  AUTH_SIGN_IN: "API:AUTH_SIGN_IN",
  AUTH_SIGN_IN_SUCCESS: "AUTH_SIGN_IN_SUCCESS",
  AUTH_SIGN_IN_FAILURE: "AUTH_SIGN_IN_FAILURE",

  AUTH_LOGOUT: "AUTH_LOGOUT",

  AUTH_GET_PROFILE: "API:AUTH_GET_PROFILE",
  AUTH_GET_PROFILE_SUCCESS: "AUTH_GET_PROFILE_SUCCESS",
  AUTH_GET_PROFILE_FAILURE: "AUTH_GET_PROFILE_FAILURE",
};
